src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Animal", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Animal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getAnimal(): ?Animal
    {
        return $this->Animal;
    }

    public function setAnimal(?Animal $Animal): self
    {
        $this->Animal = $Animal;

        return $this;
    }
}

templates/compte/compte.html.twig
{% extends "base.html.twig" %}

{% block body %}
<style>
    body {
        background-image: url(https://wallpapercave.com/wp/wp3157716.jpg);
        background-size: cover;
    }
</style>
<h1> Salut {{app.user.username}} Bienvenue dans ton auberge !</h1>

<div class="container-fluid">
    <div class="row">
        <div class="card m-4 col-4">
            <img src="{{app.user.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Nom: {{app.user.name}} <br> Prenom: {{app.user.firstName}}</h5>
                <p class="card-text">Email: {{app.user.email}}</p>
                <p class="card-text">Adresse: {{app.user.address}}</p>
                <p class="card-text">Telephone: {{app.user.phoneNumber}}</p>
            </div>
        </div>
    </div>
    <div class="row">
        <a href="{{ path('modify', {user: app.user.id}) }}" class="btn btn-warning col-3"> modifier votre compte</a>
        <a href="{{ path('modifyMdp', {user: app.user.id}) }}" class="btn btn-danger col-3"> changer de mot de
            passe</a>
    </div>
    {% endblock body %}

templates/compte/modifyCompte.html.twig
{% extends "base.html.twig" %}

{% block body %}
<style>
    body {
        background-image: url(http://maximumwallhd.com/wp-content/uploads/2017/03/wallpaper-image-animaux-en-ete-15.jpg);
        background-size: cover;
    }
</style>
    {{form_start(form)}}
    {{ form_row(form.username)}}
    {{ form_row(form.name) }}
    {{ form_row(form.firstName) }}
    {{ form_row(form.email) }}
    {{ form_row(form.address) }}
    {{ form_row(form.phoneNumber) }}
    {{ form_row(form.fileImage, {'required': 'false'}) }}
    <button class="btn btn-warning">modify</button>
    {{form_end(form)}}
{% endblock body %}